export const TitleConstants = {
    fullNameRequired: "Full Name is required.",
    fullNameMaxLength: "Full Name cannot exceed 50 characters.",
    emailRequired: "Email is required.",
    emailInvalid: "Please enter a valid email address.",
    passwordRequired: "Password is required.",
    passwordMinLength: "Password must be at least 8 characters.",
    passwordInvalid: "Password can only contain letters and numbers.",
    createAccountTitle: "Create Account",
    agreeTermsLabel: "I agree with terms and privacy",
    signUpButtonTitle: "Sign Up",
    termsAndPrivacyError: "You must agree to the terms and privacy policy.",
    fullNameLabel: "Full Name",             
    emailLabel: "Email",                   
    passwordLabel: "Password",              
    fullNamePlaceholder: "Enter your full name",
    emailPlaceholder: "Enter your email",  
    passwordPlaceholder: "Enter your password", 
    signUpFailed: "Sign up failed. Please try again."
};
